export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as HeroSection } from "./HeroSection";
export { default as ProblemSection } from "./ProblemSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as HowItWorksSection } from "./HowItWorksSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as TrustSection } from "./TrustSection";
export { default as CTASection } from "./CTASection";
